# SELECT COUNT(*) AS COUNT
# FROM ECOLI_DATA
# WHERE (SUBSTRING(CONV(GENOTYPE, 10, 2),2,1) = 0 
#        AND SUBSTRING(CONV(GENOTYPE, 10, 2),3,1) = 1)  
# OR (SUBSTRING(CONV(GENOTYPE, 10, 2),2,1) = 0 
#     AND SUBSTRING(CONV(GENOTYPE, 10, 2),1,1) = 1 );

SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE GENOTYPE & 2 = 0 AND (GENOTYPE & 4 = 4 OR GENOTYPE & 1 = 1)