# SELECT PARENT_ID As ID , COUNT(*) AS CHILD_COUNT
# FROM ECOLI_DATA
# WHERE PARENT_ID IN (SELECT ID FROM ECOLI_DATA)
# GROUP BY PARENT_ID
# ORDER BY ID

SELECT  ED1.ID, COUNT(ED2.ID) AS CHILD_COUNT
FROM ECOLI_DATA ED1
LEFT JOIN ECOLI_DATA ED2
ON ED1.ID = ED2.PARENT_ID
GROUP BY ED1.ID


            
                    
# SELECT PARENT_ID, COUNT(*)
# FROM ECOLI_DATA ED
# WHERE PARENT_ID IN (SELECT ID
#                     FROM ECOLI_DATA
#                     WHERE ID IN (SELECT IFNULL(PARENT_ID,0) FROM ECOLI_DATA))
# GROUP BY PARENT_ID;

