SELECT CAR_ID , IF(AVAILABILITY = 1, "대여중", "대여 가능")
FROM (SELECT CAR_ID, SUM(IF('2022-10-16' BETWEEN START_DATE AND END_DATE, 1, 0)) AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID) x
ORDER BY 1 DESC



# SELECT CAR_ID,
#     IF(MAX(IF(DATE_FORMAT(START_DATE, "%Y-%m-%d") = "2022-10-16" 
#        OR DATE_FORMAT(END_DATE, "%Y-%m-%d") = "2022-10-16", 1, 0)), "대여중" , "대여 가능") AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY 1 DESC;