SELECT  ED1.ID,
        ED1.GENOTYPE AS "GENOTYPE",
        ED2.GENOTYPE AS "PARENT_GENOTYPE"
FROM ECOLI_DATA ED1
LEFT JOIN ECOLI_DATA ED2
ON ED1.PARENT_ID = ED2.ID
WHERE ED1.GENOTYPE & ED2.GENOTYPE = ED2.GENOTYPE
ORDER BY ED1.ID ASC

# 부모의 형
# 부모의 형질 보유
#