SELECT 
    YEAR(ED.DIFFERENTIATION_DATE) AS "YEAR",
    (ED2.MAX - ED.SIZE_OF_COLONY) AS YEAR_DEV,
    ED.ID
FROM ECOLI_DATA ED
JOIN ( 
    SELECT 
        MAX(SIZE_OF_COLONY) AS "MAX", 
        YEAR(DIFFERENTIATION_DATE) AS "YEAR"
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) ED2
ON YEAR(ED.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;



