SELECT  SUM(HG.SCORE) AS SCORE, HG.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_DEPARTMENT HD
JOIN HR_EMPLOYEES HE
ON HD.DEPT_ID = HE.DEPT_ID
JOIN HR_GRADE HG
ON HG.EMP_NO = HE.EMP_NO
WHERE HG.YEAR = 2022
GROUP BY HE.EMP_NO 
ORDER BY SCORE DESC
LIMIT 1;