SELECT CONCAT("/home/grep/src/" ,ug.board_id ,"/", uf.file_id , uf.file_name, uf.file_ext) as FILE_PATH
FROM USED_GOODS_BOARD UG
JOIN USED_GOODS_FILE UF
ON UG.BOARD_ID = UF.BOARD_ID
WHERE  UG.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY UF.FILE_ID DESC

