SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE
FROM (SELECT IF(LENGTH <= 10 , 10, LENGTH) AS LENGTH , ID , FISH_TYPE, TIME
FROM FISH_INFO) X
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE

